### ISSUE TITLE
Creating catalog repo fails due to bad credentials

### ISSUE THREAD

**Issue by rly** [nwb-extensions/staged-extensions#33]
```
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "[https://docs.github.com/rest"}](https://docs.github.com/rest%22%7D)
fatal: could not read Password for '[https://***@github.com'](https://***@github.com%27/): terminal prompts disabled
```

Also may be worth moving from CircleCI to GitHub Actions

**Comment by rly** [comment]
`ndx-hierarchical-behavior-record` needs to be added to the org / catalog

**Comment by weiglszonja** [comment]
@rly @luiztauffer 

> ndx-hierarchical-behavior-record needs to be added to the org / catalog

Connecting the dots for https://github.com/nwb-extensions/staged-extensions/pull/30 and the open issue at https://github.com/catalystneuro/ndx-hierarchical-behavioral-data/issues/9, which can be probably closed. This extension was already merged but not showing up in https://nwb-extensions.github.io.
